server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://192.168.1.20:5432/fraud
    password: 'password'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect